# # Step 3
# SRCS=main.c arithmetic.c user_interface.c
# HEADER_DIR=../include

# main.out : $(SRCS)
# 	gcc  $^ -I$(HEADER_DIR) -o ../bin/$@
# # ---

# # Step 4
SRC_DIR=./src
SRCS=$(SRC_DIR)/main.c $(SRC_DIR)/arithmetic.c $(SRC_DIR)/user_interface.c
HEADER_DIR=./include

main1.out : $(SRCS)
	gcc  $^ -I$(HEADER_DIR) -o ./bin/$@
# # ---